version: '3'
services:
  web:
    image: nginx
    volumes:
    - nginx_templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=nginx.localhost
    - NGINX_PORT=80
volumes:
  nginx_templates:    