apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f nginx-compose.yaml convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
