apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f nginx-compose.yaml convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f nginx-compose.yaml convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: NGINX_HOST
              value: nginx.localhost
            - name: NGINX_PORT
              value: "80"
          image: nginx
          name: web
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/templates
              name: nginx-templates
      restartPolicy: Always
      volumes:
        - name: nginx-templates
          persistentVolumeClaim:
            claimName: nginx-templates
status: {}
